### ISSUE TITLE
Search by Breed or Category doesn't require API Key

### ISSUE THREAD

**Issue by mattangriffel** [AdenForshaw/theCatAPI-website#40]
Although [the documentation](https://docs.thecatapi.com/example-by-category) states that both Search by Category and Search by Breed requires an API Key for authentication, I can access the whole API without an API key. I normally wouldn't be complaining except that I'm trying to use this library as an example API for a class I'm teaching and want to demonstrate the purpose of API Keys.

**Comment by AdenForshaw** [comment]
this has now been resolved
