### ISSUE TITLE
API call returns always 10 images

### ISSUE THREAD

**Issue by nekolii7** [AdenForshaw/theCatAPI-website#48]
I used the Dog API for n example page to test some Vue stuff on.
Unfortunately the API call is no longer working as expected:
https://api.thedogapi.com/v1/images/search?limit=20
this returns always 10 pictures to me and didn't get me the breed information back as well (which I used to display the dogs names below the image).
Why does it not longer provide the information said in the api reference:
https://docs.thedogapi.com/api-reference/images/images-search ?

**Comment by AdenForshaw** [comment]
@nekolii7 You need to use an API KEy to get more than 10 images, and the breed info
